import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Category from "@/commonTypes/commonTypes";
import axios from "axios";
import Navbar from "@/components/homePage/Navbar/Navbar";
import SeachBar from "@/components/homePage/SearchBar/SeachBar";
import Avatar from "@/components/homePage/Avatar/Avatar";
import Drawar from "@/components/homePage/Drawar/Drawar";
import CategoryNav from "@/components/homePage/CategoryNav/CategoryNav";
import CategoryItems from "@/components/homePage/CategoryItems/CategoryItems";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await axios.get("http://localhost:5000/");
  const categorys: Category[] = res.data.categorys;
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#EBEEF2" }}>
        <div className="flex w-full">
          <div className="w-[10%]">
            <Navbar />
          </div>
          <div className="mt-5 mx-8  w-full">
            <div className="flex justify-between">
              <h1 className="text-2xl">Dua Page</h1>
              <div className="flex space-x-4 items-center">
                <SeachBar />
                <Avatar />
                <Drawar />
              </div>
            </div>
            <div className="flex gap-8">
              <div className="w-[66%]">
                <CategoryNav data={categorys} />
              </div>
              <div className=" flex-grow mt-4">{children}</div>
            </div>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
